import { randomUUID } from 'node:crypto'
import { join } from 'node:path'
import { DatabaseSync } from 'node:sqlite'

import { assertApprovalBinding, assertAuthority, authorize, canonicalJson, contentHash, ContractError, createAuditEvent } from './laboratory-contract.js'
import type { AuditEvent, Authority, CapabilityGrant, LaboratoryId, Operation, TrustedInvocationContext } from './laboratory-contract.js'
import { LocalMemoryStore } from './local-memory-store.js'

export interface WorkflowInvocation { readonly context: TrustedInvocationContext; readonly capability: CapabilityGrant; readonly authority: Authority }
export interface ComputeLimits { readonly maxBytes: number; readonly maxObjectBytes: number; readonly maxObjects: number }
export interface ComputeObject { readonly id: LaboratoryId<'object'>; readonly revision: number; readonly hash: `sha256:${string}`; readonly size: number; readonly state: 'active' | 'released'; readonly expiresAt: string | null }
export interface ComputeSnapshot { readonly id: LaboratoryId<'object'>; readonly sourceId: LaboratoryId<'object'>; readonly sourceRevision: number; readonly hash: `sha256:${string}`; readonly size: number; readonly createdAt: string }
export interface WorkingRevision<T = unknown> { readonly id: LaboratoryId<'object'>; readonly key: string; readonly revision: number; readonly value: T; readonly hash: `sha256:${string}`; readonly proposalId: LaboratoryId<'proposal'>; readonly committedAt: string }
export interface WorkingProposal<T = unknown> { readonly id: LaboratoryId<'proposal'>; readonly key: string; readonly baseRevision: number; readonly value: T; readonly hash: `sha256:${string}`; readonly state: 'proposed' | 'approved' | 'rejected' | 'superseded'; readonly createdAt: string }
export interface WorkflowApprovalRecord { readonly workspaceId: LaboratoryId<'workspace'>; readonly proposalId: LaboratoryId<'proposal'>; readonly proposalHash: `sha256:${string}`; readonly decision: 'approved' }
export interface ArtifactProvenance { readonly operation: string; readonly parametersHash: `sha256:${string}`; readonly softwareVersion: string; readonly validationId: LaboratoryId<'validation'> | null }
export interface Artifact { readonly id: LaboratoryId<'object'>; readonly hash: `sha256:${string}`; readonly size: number; readonly schema: unknown; readonly schemaHash: `sha256:${string}`; readonly parentIds: readonly LaboratoryId<'object'>[]; readonly provenance: ArtifactProvenance; readonly createdAt: string }

type ComputeRow = { id: string; revision: number; hash: string; size: number; state: 'active' | 'released'; expires_at: string | null }
type ProposalRow = { id: string; key: string; base_revision: number; value_json: string; hash: string; state: WorkingProposal['state']; created_at: string }
type RevisionRow = { id: string; key: string; revision: number; value_json: string; hash: string; proposal_id: string; committed_at: string }
type ArtifactRow = { id: string; hash: string; size: number; schema_json: string; schema_hash: string; parents_json: string; provenance_json: string; created_at: string }

export class MemoryWorkflowError extends Error { constructor(readonly code: string, message: string) { super(`[${code}] ${message}`); this.name = 'MemoryWorkflowError' } }
function fail(code: string, message: string): never { throw new MemoryWorkflowError(code, message) }
function positive(value: number, name: string): void { if (!Number.isSafeInteger(value) || value <= 0) fail('INVALID_COMPUTE_LIMIT', `${name} must be a positive safe integer`) }

export class MemoryWorkflows {
  private readonly database: DatabaseSync
  private readonly clock: () => Date
  private readonly limits: ComputeLimits
  private closed = false

  constructor(readonly store: LocalMemoryStore, options: { readonly now?: () => Date; readonly computeLimits?: ComputeLimits } = {}) {
    this.clock = options.now ?? (() => new Date())
    this.limits = options.computeLimits ?? { maxBytes: 16 * 1024 * 1024, maxObjectBytes: 1024 * 1024, maxObjects: 128 }
    positive(this.limits.maxBytes, 'maxBytes'); positive(this.limits.maxObjectBytes, 'maxObjectBytes'); positive(this.limits.maxObjects, 'maxObjects')
    if (this.limits.maxObjectBytes > this.limits.maxBytes) fail('INVALID_COMPUTE_LIMIT', 'maxObjectBytes cannot exceed maxBytes')
    this.database = new DatabaseSync(join(store.root, 'workflows.sqlite3'))
    this.database.exec('PRAGMA foreign_keys = ON; PRAGMA journal_mode = WAL; PRAGMA synchronous = FULL;')
    this.migrate()
  }

  private migrate(): void {
    const version = (this.database.prepare('PRAGMA user_version').get() as { user_version: number }).user_version
    if (version > 1) fail('UNSUPPORTED_WORKFLOW_VERSION', `workflow schema version ${version} is unsupported`)
    if (version === 0) this.database.exec(`BEGIN IMMEDIATE;
      CREATE TABLE compute_objects (workspace_id TEXT NOT NULL, id TEXT NOT NULL, revision INTEGER NOT NULL, hash TEXT NOT NULL, size INTEGER NOT NULL, state TEXT NOT NULL CHECK(state IN ('active','released')), expires_at TEXT, PRIMARY KEY(workspace_id,id));
      CREATE TABLE compute_snapshots (workspace_id TEXT NOT NULL, id TEXT NOT NULL, source_id TEXT NOT NULL, source_revision INTEGER NOT NULL, hash TEXT NOT NULL, size INTEGER NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(workspace_id,id));
      CREATE TABLE working_proposals (workspace_id TEXT NOT NULL, id TEXT NOT NULL, key TEXT NOT NULL, base_revision INTEGER NOT NULL, value_json TEXT NOT NULL, hash TEXT NOT NULL, state TEXT NOT NULL CHECK(state IN ('proposed','approved','rejected','superseded')), created_at TEXT NOT NULL, decided_at TEXT, decided_by TEXT, PRIMARY KEY(workspace_id,id));
      CREATE TABLE working_revisions (workspace_id TEXT NOT NULL, id TEXT NOT NULL, key TEXT NOT NULL, revision INTEGER NOT NULL, value_json TEXT NOT NULL, hash TEXT NOT NULL, proposal_id TEXT NOT NULL, committed_at TEXT NOT NULL, PRIMARY KEY(workspace_id,key,revision), UNIQUE(workspace_id,id));
      CREATE TABLE artifacts (workspace_id TEXT NOT NULL, id TEXT NOT NULL, hash TEXT NOT NULL, size INTEGER NOT NULL, schema_json TEXT NOT NULL, schema_hash TEXT NOT NULL, parents_json TEXT NOT NULL, provenance_json TEXT NOT NULL, created_at TEXT NOT NULL, PRIMARY KEY(workspace_id,id));
      CREATE TABLE workflow_audit (sequence INTEGER PRIMARY KEY AUTOINCREMENT, event_json TEXT NOT NULL);
      PRAGMA user_version = 1; COMMIT;`)
  }

  private now(): string { return this.clock().toISOString() }
  private ensureOpen(): void { if (this.closed) fail('WORKFLOWS_CLOSED', 'memory workflows are closed') }
  private audit(invocation: WorkflowInvocation, operation: Operation, targetId: LaboratoryId | null, input: unknown, outcome: 'succeeded' | 'rejected' | 'failed', errorCode: string | null): void {
    const event = createAuditEvent({ eventId: `event:${randomUUID()}`, workspaceId: invocation.context.workspaceId, actorId: invocation.context.actorId, callId: invocation.context.callId, operation, targetId, capabilityId: invocation.capability.capabilityId, occurredAt: this.now(), outcome, errorCode, input })
    this.database.prepare('INSERT INTO workflow_audit(event_json) VALUES (?)').run(canonicalJson(event))
  }
  private perform<T>(invocation: WorkflowInvocation, operation: Operation, targetId: LaboratoryId | null, input: unknown, action: () => T): T {
    this.ensureOpen()
    try { assertAuthority(operation, invocation.authority); authorize(invocation.context, invocation.capability, operation, this.now()); const result = action(); this.audit(invocation, operation, targetId, input, 'succeeded', null); return result }
    catch (error) { const code = error instanceof ContractError || error instanceof MemoryWorkflowError ? error.code : 'INTERNAL_ERROR'; this.audit(invocation, operation, targetId, input, code === 'INTERNAL_ERROR' ? 'failed' : 'rejected', code); throw error }
  }
  private workspace(invocation: WorkflowInvocation): LaboratoryId<'workspace'> { this.store.reopenWorkspace(invocation.context.workspaceId); return invocation.context.workspaceId }
  private computeRow(workspaceId: string, id: string): ComputeRow { const row = this.database.prepare('SELECT id,revision,hash,size,state,expires_at FROM compute_objects WHERE workspace_id=? AND id=?').get(workspaceId,id) as ComputeRow | undefined; if (!row) fail('COMPUTE_NOT_FOUND','compute object is not visible in this workspace'); return row }
  private computeResult(row: ComputeRow): ComputeObject { return { id: row.id as LaboratoryId<'object'>, revision: row.revision, hash: row.hash as `sha256:${string}`, size: row.size, state: row.state, expiresAt: row.expires_at } }
  private activeComputeUsage(workspaceId: string): { count: number; bytes: number } { return this.database.prepare("SELECT COUNT(*) AS count, COALESCE(SUM(size),0) AS bytes FROM compute_objects WHERE workspace_id=? AND state='active'").get(workspaceId) as { count: number; bytes: number } }

  createCompute(invocation: WorkflowInvocation, bytes: Uint8Array, expiresAt: string | null = null): ComputeObject {
    return this.perform(invocation,'compute.create',null,{ size: bytes.byteLength, expiresAt },() => { const workspaceId=this.workspace(invocation); if (bytes.byteLength>this.limits.maxObjectBytes) fail('COMPUTE_OBJECT_TOO_LARGE','compute object exceeds its per-object byte limit'); const usage=this.activeComputeUsage(workspaceId); if(usage.count>=this.limits.maxObjects) fail('COMPUTE_OBJECT_LIMIT','compute object quota is exhausted'); if(usage.bytes+bytes.byteLength>this.limits.maxBytes) fail('COMPUTE_BYTE_LIMIT','active compute byte quota would be exceeded'); const payload=this.store.putPayload(workspaceId,bytes,expiresAt); const id=`object:${randomUUID()}` as const; this.database.prepare('INSERT INTO compute_objects VALUES (?,?,?,?,?,?,?)').run(workspaceId,id,1,payload.hash,payload.size,'active',expiresAt); return {id,revision:1,hash:payload.hash,size:payload.size,state:'active',expiresAt} })
  }
  readCompute(invocation: WorkflowInvocation, id: LaboratoryId<'object'>): Uint8Array { return this.perform(invocation,'compute.read',id,{id},()=>{ const row=this.computeRow(this.workspace(invocation),id); if(row.state!=='active') fail('COMPUTE_RELEASED','compute object has been released'); return this.store.readPayload(invocation.context.workspaceId,row.hash) }) }
  updateCompute(invocation: WorkflowInvocation, id: LaboratoryId<'object'>, bytes: Uint8Array): ComputeObject { return this.perform(invocation,'compute.update',id,{id,size:bytes.byteLength},()=>{ const workspaceId=this.workspace(invocation); const row=this.computeRow(workspaceId,id); if(row.state!=='active') fail('COMPUTE_RELEASED','compute object has been released'); if(bytes.byteLength>this.limits.maxObjectBytes) fail('COMPUTE_OBJECT_TOO_LARGE','compute object exceeds its per-object byte limit'); const usage=this.activeComputeUsage(workspaceId); if(usage.bytes-row.size+bytes.byteLength>this.limits.maxBytes) fail('COMPUTE_BYTE_LIMIT','active compute byte quota would be exceeded'); const payload=this.store.putPayload(workspaceId,bytes,row.expires_at); this.database.prepare('UPDATE compute_objects SET revision=?,hash=?,size=? WHERE workspace_id=? AND id=?').run(row.revision+1,payload.hash,payload.size,workspaceId,id); return {...this.computeResult(row),revision:row.revision+1,hash:payload.hash,size:payload.size} }) }
  snapshotCompute(invocation: WorkflowInvocation, id: LaboratoryId<'object'>): ComputeSnapshot { return this.perform(invocation,'compute.snapshot',id,{id},()=>{ const workspaceId=this.workspace(invocation); const row=this.computeRow(workspaceId,id); if(row.state!=='active') fail('COMPUTE_RELEASED','compute object has been released'); const snapshotId=`object:${randomUUID()}` as const; const createdAt=this.now(); this.database.prepare('INSERT INTO compute_snapshots VALUES (?,?,?,?,?,?,?)').run(workspaceId,snapshotId,id,row.revision,row.hash,row.size,createdAt); return {id:snapshotId,sourceId:id,sourceRevision:row.revision,hash:row.hash as `sha256:${string}`,size:row.size,createdAt} }) }
  releaseCompute(invocation: WorkflowInvocation, id: LaboratoryId<'object'>): ComputeObject { return this.perform(invocation,'compute.release',id,{id},()=>{ const workspaceId=this.workspace(invocation); const row=this.computeRow(workspaceId,id); if(row.state!=='active') fail('COMPUTE_RELEASED','compute object has already been released'); this.database.prepare("UPDATE compute_objects SET state='released' WHERE workspace_id=? AND id=?").run(workspaceId,id); return {...this.computeResult(row),state:'released'} }) }

  proposeWorking<T>(invocation: WorkflowInvocation, key: string, value: T): WorkingProposal<T> { return this.perform(invocation,'working.propose',null,{key,value},()=>{ const workspaceId=this.workspace(invocation); if(!key) fail('INVALID_WORKING_KEY','working key must not be empty'); const current=(this.database.prepare('SELECT COALESCE(MAX(revision),0) AS revision FROM working_revisions WHERE workspace_id=? AND key=?').get(workspaceId,key) as {revision:number}).revision; const id=`proposal:${randomUUID()}` as const; const createdAt=this.now(); const proposalValue={key,baseRevision:current,value}; const hash=contentHash(proposalValue); this.database.prepare('INSERT INTO working_proposals(workspace_id,id,key,base_revision,value_json,hash,state,created_at) VALUES (?,?,?,?,?,?,?,?)').run(workspaceId,id,key,current,canonicalJson(value),hash,'proposed',createdAt); return {id,key,baseRevision:current,value,hash,state:'proposed',createdAt} }) }
  readWorking<T=unknown>(invocation: WorkflowInvocation,key:string): WorkingRevision<T>|null { return this.perform(invocation,'working.read',null,{key},()=>{ const workspaceId=this.workspace(invocation); const row=this.database.prepare('SELECT id,key,revision,value_json,hash,proposal_id,committed_at FROM working_revisions WHERE workspace_id=? AND key=? ORDER BY revision DESC LIMIT 1').get(workspaceId,key) as RevisionRow|undefined; return row ? this.revisionResult<T>(row) : null }) }
  workingHistory<T=unknown>(invocation: WorkflowInvocation,key:string):readonly WorkingRevision<T>[] { return this.perform(invocation,'working.read',null,{key,history:true},()=>{ const workspaceId=this.workspace(invocation); const rows=this.database.prepare('SELECT id,key,revision,value_json,hash,proposal_id,committed_at FROM working_revisions WHERE workspace_id=? AND key=? ORDER BY revision').all(workspaceId,key) as RevisionRow[]; return rows.map(row=>this.revisionResult<T>(row)) }) }
  approveWorking<T=unknown>(invocation: WorkflowInvocation, proposalId: LaboratoryId<'proposal'>, approval: WorkflowApprovalRecord): WorkingRevision<T> { return this.perform(invocation,'working.approve',proposalId,{proposalId,approval},()=>{ const workspaceId=this.workspace(invocation); const proposal=this.proposalRow(workspaceId,proposalId); if(proposal.state!=='proposed') fail('PROPOSAL_NOT_PENDING','proposal is no longer pending'); assertApprovalBinding(workspaceId,proposalId,proposal.hash,approval); const current=(this.database.prepare('SELECT COALESCE(MAX(revision),0) AS revision FROM working_revisions WHERE workspace_id=? AND key=?').get(workspaceId,proposal.key) as {revision:number}).revision; if(current!==proposal.base_revision) fail('STALE_PROPOSAL','working state changed after this proposal was created'); const committedAt=this.now(); const id=`object:${randomUUID()}` as const; this.database.exec('BEGIN IMMEDIATE'); try { this.database.prepare('INSERT INTO working_revisions VALUES (?,?,?,?,?,?,?,?)').run(workspaceId,id,proposal.key,current+1,proposal.value_json,proposal.hash,proposalId,committedAt); this.database.prepare("UPDATE working_proposals SET state='approved',decided_at=?,decided_by=? WHERE workspace_id=? AND id=?").run(committedAt,invocation.context.actorId,workspaceId,proposalId); this.database.exec('COMMIT') } catch(error){this.database.exec('ROLLBACK');throw error} return {id,key:proposal.key,revision:current+1,value:JSON.parse(proposal.value_json) as T,hash:proposal.hash as `sha256:${string}`,proposalId,committedAt} }) }
  rejectWorking(invocation: WorkflowInvocation,proposalId:LaboratoryId<'proposal'>): WorkingProposal { return this.decideProposal(invocation,proposalId,'working.reject','rejected') }
  supersedeWorking(invocation: WorkflowInvocation,proposalId:LaboratoryId<'proposal'>): WorkingProposal { return this.decideProposal(invocation,proposalId,'working.supersede','superseded') }
  private decideProposal(invocation:WorkflowInvocation,proposalId:LaboratoryId<'proposal'>,operation:'working.reject'|'working.supersede',state:'rejected'|'superseded'):WorkingProposal { return this.perform(invocation,operation,proposalId,{proposalId},()=>{ const workspaceId=this.workspace(invocation); const row=this.proposalRow(workspaceId,proposalId); if(row.state!=='proposed') fail('PROPOSAL_NOT_PENDING','proposal is no longer pending'); this.database.prepare('UPDATE working_proposals SET state=?,decided_at=?,decided_by=? WHERE workspace_id=? AND id=?').run(state,this.now(),invocation.context.actorId,workspaceId,proposalId); return this.proposalResult(row,state) }) }
  private proposalRow(workspaceId:string,id:string):ProposalRow { const row=this.database.prepare('SELECT id,key,base_revision,value_json,hash,state,created_at FROM working_proposals WHERE workspace_id=? AND id=?').get(workspaceId,id) as ProposalRow|undefined; if(!row) fail('PROPOSAL_NOT_FOUND','proposal is not visible in this workspace'); return row }
  private proposalResult<T=unknown>(row:ProposalRow,state=row.state):WorkingProposal<T>{return {id:row.id as LaboratoryId<'proposal'>,key:row.key,baseRevision:row.base_revision,value:JSON.parse(row.value_json) as T,hash:row.hash as `sha256:${string}`,state,createdAt:row.created_at}}
  private revisionResult<T>(row:RevisionRow):WorkingRevision<T>{return{id:row.id as LaboratoryId<'object'>,key:row.key,revision:row.revision,value:JSON.parse(row.value_json) as T,hash:row.hash as `sha256:${string}`,proposalId:row.proposal_id as LaboratoryId<'proposal'>,committedAt:row.committed_at}}

  createArtifact(invocation:WorkflowInvocation,bytes:Uint8Array,schema:unknown,provenance:ArtifactProvenance):Artifact{return this.saveArtifact(invocation,'artifact.create',[],bytes,schema,provenance)}
  deriveArtifact(invocation:WorkflowInvocation,parentIds:readonly LaboratoryId<'object'>[],bytes:Uint8Array,schema:unknown,provenance:ArtifactProvenance):Artifact{if(parentIds.length===0)fail('ARTIFACT_PARENT_REQUIRED','a derivation requires at least one parent');return this.saveArtifact(invocation,'artifact.derive',parentIds,bytes,schema,provenance)}
  private saveArtifact(invocation:WorkflowInvocation,operation:'artifact.create'|'artifact.derive',parentIds:readonly LaboratoryId<'object'>[],bytes:Uint8Array,schema:unknown,provenance:ArtifactProvenance):Artifact{return this.perform(invocation,operation,parentIds[0]??null,{parentIds,size:bytes.byteLength,schema,provenance},()=>{const workspaceId=this.workspace(invocation); for(const parent of parentIds)this.artifactRow(workspaceId,parent); const payload=this.store.putPayload(workspaceId,bytes); const id=`object:${randomUUID()}` as const; const createdAt=this.now(); const schemaHash=contentHash(schema); this.database.prepare('INSERT INTO artifacts VALUES (?,?,?,?,?,?,?,?,?)').run(workspaceId,id,payload.hash,payload.size,canonicalJson(schema),schemaHash,canonicalJson(parentIds),canonicalJson(provenance),createdAt); return{id,hash:payload.hash,size:payload.size,schema,schemaHash,parentIds:[...parentIds],provenance,createdAt}})}
  readArtifact(invocation:WorkflowInvocation,id:LaboratoryId<'object'>):Uint8Array{return this.perform(invocation,'artifact.read',id,{id},()=>{const row=this.artifactRow(this.workspace(invocation),id);return this.store.readPayload(invocation.context.workspaceId,row.hash)})}
  inspectArtifact(invocation:WorkflowInvocation,id:LaboratoryId<'object'>):Artifact{return this.perform(invocation,'artifact.read',id,{id,metadataOnly:true},()=>this.artifactResult(this.artifactRow(this.workspace(invocation),id)))}
  private artifactRow(workspaceId:string,id:string):ArtifactRow{const row=this.database.prepare('SELECT id,hash,size,schema_json,schema_hash,parents_json,provenance_json,created_at FROM artifacts WHERE workspace_id=? AND id=?').get(workspaceId,id) as ArtifactRow|undefined;if(!row)fail('ARTIFACT_NOT_FOUND','artifact is not visible in this workspace');return row}
  private artifactResult(row:ArtifactRow):Artifact{return{id:row.id as LaboratoryId<'object'>,hash:row.hash as `sha256:${string}`,size:row.size,schema:JSON.parse(row.schema_json),schemaHash:row.schema_hash as `sha256:${string}`,parentIds:JSON.parse(row.parents_json) as LaboratoryId<'object'>[],provenance:JSON.parse(row.provenance_json) as ArtifactProvenance,createdAt:row.created_at}}
  auditEvents():readonly AuditEvent[]{this.ensureOpen();return (this.database.prepare('SELECT event_json FROM workflow_audit ORDER BY sequence').all() as {event_json:string}[]).map(row=>JSON.parse(row.event_json) as AuditEvent)}
  close():void{if(!this.closed){this.database.close();this.closed=true}}
}
