# Axiom V1 offline dependency locations and version/hash gates (F009, T01).
#
# Contract: specs/03-build-and-dependencies.md
#   * Only the fixed source-directory + add_subdirectory style is used for V1;
#     bootstrap materialises deps/sources/<name> and CMake only reads it.
#   * No vcpkg/Conan/second lock system.
#   * A missing or mismatched dependency is a hard configure error; the
#     implementation must never substitute another version silently.
#   * Qt is a preinstalled package; its location is provided through
#     CMakeUserPresets.json (machine-local, never committed).
#
# Every dependency below is declared in contracts/dependencies-baseline.json and
# resolved to exact bytes in deps/lock.json by the T01 bootstrap. Nothing here
# downloads during configure: V1 builds offline.

include_guard(GLOBAL)

set(AXIOM_DEPS_ROOT "${CMAKE_CURRENT_LIST_DIR}/../deps" CACHE PATH
    "Root of the frozen, read-only dependency cache")
set(AXIOM_DEPS_SOURCES "${AXIOM_DEPS_ROOT}/sources" CACHE PATH
    "Frozen dependency source directories (bootstrap output)")

# Minimal, dependency-free extraction of one field of one dependency entry.
# The lock file is generated by this project's bootstrap, never by a model
# command string, and is a closed schema.
function(axiom_lock_field name field out_var)
    if(NOT AXIOM_DEPS_LOCK_JSON)
        message(FATAL_ERROR
            "deps/lock.json was not loaded. A target needs frozen dependency "
            "bytes but the lock file is missing; run the bootstrap first "
            "(specs/03 forbids fabricating hashes).")
    endif()
    string(JSON _value ERROR_VARIABLE _err GET "${AXIOM_DEPS_LOCK_JSON}"
        dependencies "${name}" "${field}")
    if(_err)
        message(FATAL_ERROR
            "deps/lock.json has no '${field}' for dependency '${name}': ${_err}")
    endif()
    set(${out_var} "${_value}" PARENT_SCOPE)
endfunction()

# Loads deps/lock.json if present. Absence is not fatal by itself: a fresh
# checkout can still configure the parts that need no frozen bytes (and run the
# bootstrap). Any target that actually consumes a dependency fails loudly.
function(axiom_load_lock)
    if(EXISTS "${AXIOM_DEPS_ROOT}/lock.json")
        file(READ "${AXIOM_DEPS_ROOT}/lock.json" _json)
        set(AXIOM_DEPS_LOCK_JSON "${_json}" PARENT_SCOPE)
        message(STATUS "deps/lock.json loaded from ${AXIOM_DEPS_ROOT}")
    else()
        set(AXIOM_DEPS_LOCK_JSON "" PARENT_SCOPE)
        message(STATUS
            "deps/lock.json is absent: dependency-consuming targets will fail "
            "until the bootstrap has run.")
    endif()
endfunction()

# Verifies one frozen dependency directory against the locked digest.
function(axiom_require_dependency name)
    axiom_lock_field("${name}" "version" _version)
    axiom_lock_field("${name}" "sha256" _sha256)
    axiom_lock_field("${name}" "source_dir" _source_dir)

    if(_sha256 STREQUAL "" OR _sha256 STREQUAL "null")
        message(FATAL_ERROR
            "deps/lock.json entry '${name}' has no resolved sha256. "
            "specs/03: a null/unresolved hash must fail the normal build.")
    endif()

    set(_abs "${AXIOM_DEPS_ROOT}/${_source_dir}")
    if(NOT IS_DIRECTORY "${_abs}")
        message(FATAL_ERROR
            "Dependency '${name}' version ${_version} is not present at "
            "'${_abs}'. Run the bootstrap on a networked machine; V1 builds "
            "offline and never downloads during configure.")
    endif()

    if(NOT EXISTS "${_abs}/.axiom-lock-verified")
        message(FATAL_ERROR
            "Dependency '${name}' at '${_abs}' has no .axiom-lock-verified "
            "marker; its bytes were not verified against deps/lock.json.")
    endif()
    file(READ "${_abs}/.axiom-lock-verified" _marker)
    string(STRIP "${_marker}" _marker)
    if(NOT _marker STREQUAL _sha256)
        message(FATAL_ERROR
            "Dependency '${name}' bytes at '${_abs}' do not match deps/lock.json "
            "(marker '${_marker}' != locked '${_sha256}').")
    endif()

    set(AXIOM_${name}_DIR "${_abs}" PARENT_SCOPE)
    set(AXIOM_${name}_VERSION "${_version}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------------------
# Qt 6.11.2 (preinstalled, shared, LGPLv3 route; see docs/LICENSE-DECISION.md)
# ---------------------------------------------------------------------------
function(axiom_find_qt)
    find_package(Qt6 6.11.2 EXACT QUIET COMPONENTS Core Network Gui Widgets)
    if(NOT Qt6_FOUND)
        message(FATAL_ERROR
            "Qt 6.11.2 (MSVC x64) was not found. specs/03 requires the exact "
            "version and forbids silently using another. Set CMAKE_PREFIX_PATH "
            "to the kit directory, e.g. C:/Qt/6.11.2/msvc2022_64, through "
            "CMakeUserPresets.json (machine-local, never committed).")
    endif()
    if(NOT Qt6Core_VERSION VERSION_EQUAL "6.11.2")
        message(FATAL_ERROR
            "Qt version ${Qt6Core_VERSION} found, but specs/03 freezes 6.11.2.")
    endif()
    # specs/03 forbids QtSql/Qml/WebEngine. They are installed in this kit, so
    # the ban is enforced here rather than by their absence.
    foreach(_forbidden Qt6::Sql Qt6::Qml Qt6::WebEngineWidgets)
        if(TARGET ${_forbidden})
            message(FATAL_ERROR
                "Forbidden Qt component ${_forbidden} is available. specs/03 "
                "allows only Core, Network (local IPC), Gui and Widgets.")
        endif()
    endforeach()
    set(AXIOM_QT_VERSION "${Qt6Core_VERSION}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------------------
# Third-party targets consumed by C01/C10 (nlohmann_json, SQLite) and tests
# (Catch2). Declared lazily so that a fresh checkout can configure.
# ---------------------------------------------------------------------------
function(axiom_third_party_nlohmann_json)
    if(TARGET axiom_nlohmann_json)
        return()
    endif()
    axiom_require_dependency(nlohmann_json)
    add_library(axiom_nlohmann_json INTERFACE)
    target_include_directories(axiom_nlohmann_json SYSTEM INTERFACE
        "${AXIOM_nlohmann_json_DIR}/include")
    set_property(TARGET axiom_nlohmann_json PROPERTY
        AXIOM_LOCKED_VERSION "${AXIOM_nlohmann_json_VERSION}")
endfunction()

function(axiom_third_party_sqlite)
    if(TARGET axiom_sqlite3)
        return()
    endif()
    axiom_require_dependency(sqlite)
    add_library(axiom_sqlite3 STATIC
        "${AXIOM_sqlite_DIR}/sqlite3.c")
    target_include_directories(axiom_sqlite3 SYSTEM PUBLIC
        "${AXIOM_sqlite_DIR}")
    # specs/03: official C API only, load_extension disabled.
    target_compile_definitions(axiom_sqlite3 PUBLIC
        SQLITE_OMIT_LOAD_EXTENSION=1
        SQLITE_THREADSAFE=1
        SQLITE_DEFAULT_FOREIGN_KEYS=1)
    set_property(TARGET axiom_sqlite3 PROPERTY
        AXIOM_LOCKED_VERSION "${AXIOM_sqlite_VERSION}")
endfunction()

function(axiom_third_party_catch2)
    if(TARGET axiom_catch2)
        return()
    endif()
    axiom_require_dependency(catch2)
    # Catch2 v3 is a CMake project; add_subdirectory is the sanctioned
    # "fixed source directory + add_subdirectory" style of specs/03.
    set(CATCH_BUILD_TESTING OFF CACHE BOOL "" FORCE)
    set(CATCH_INSTALL_DOCS OFF CACHE BOOL "" FORCE)
    set(CATCH_INSTALL_EXTRAS OFF CACHE BOOL "" FORCE)
    set(CATCH_DEVELOPMENT_BUILD OFF CACHE BOOL "" FORCE)
    add_subdirectory("${AXIOM_catch2_DIR}"
        "${CMAKE_BINARY_DIR}/_deps/catch2" EXCLUDE_FROM_ALL)
    # Catch2::Catch2WithMain is itself an ALIAS, so no second alias is created;
    # the tests link Catch2::Catch2WithMain directly.
    set_property(TARGET Catch2 PROPERTY
        AXIOM_LOCKED_VERSION "${AXIOM_catch2_VERSION}")
endfunction()
